import eslint from "@eslint/js"
import eslintConfigPrettier from "eslint-config-prettier"
import tseslint from "typescript-eslint"

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/coverage/**",
      "**/drizzle/**",
      "node_modules/**",
      // Generated by `pnpm --filter @postbag/sdk generate` from the server's live
      // /openapi.json — not hand-written, not worth holding to our style rules.
      "packages/sdk/src/schema.d.ts",
      "apps/web/src/routeTree.gen.ts",
      // Astro site: generated types, config and build scripts are plain JS/Node.
      "apps/site/.astro/**",
      "apps/site/astro.config.mjs",
      "apps/site/scripts/**",
      // These two routes import `astro:content`, whose types only exist once `astro
      // sync`/`astro check` has generated `apps/site/.astro/types.d.ts` (gitignored).
      // The root `pnpm lint` never builds the site, so on a clean checkout typed linting
      // sees the import as untyped and trips `no-unsafe-*`. `apps/site`'s own
      // `pnpm typecheck` (`astro check`) covers these files with real astro:content
      // types, so excluding them here does not lose coverage — do not rewrite them.
      "apps/site/src/pages/docs/\\[...slug\\]/index.md.ts",
      "apps/site/src/pages/llms-full.txt.ts",
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.strictTypeChecked.map((c) => ({ ...c, files: ["**/*.ts", "**/*.tsx"] })),
  ...tseslint.configs.stylisticTypeChecked.map((c) => ({ ...c, files: ["**/*.ts", "**/*.tsx"] })),
  eslintConfigPrettier,
  {
    files: ["**/*.js", "**/*.mjs", "**/*.cjs", "**/*.config.ts", "vitest.workspace.ts"],
    ...tseslint.configs.disableTypeChecked,
  },
  {
    files: ["**/*.ts", "**/*.tsx"],
    languageOptions: {
      parserOptions: {
        projectService: {
          allowDefaultProject: ["*.ts", "packages/*/*.ts", "apps/*/*.ts"],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/no-unnecessary-type-assertion": "error",
      "@typescript-eslint/prefer-readonly": "error",
      "@typescript-eslint/switch-exhaustiveness-check": "error",
      "no-param-reassign": "error",
      "@typescript-eslint/restrict-template-expressions": ["error", { allowNumber: true }],
      "@typescript-eslint/consistent-type-definitions": "off",
      "@typescript-eslint/dot-notation": ["error", { allowIndexSignaturePropertyAccess: true }],
    },
  },
)
