/** Mirrors packages/core/src/errors.ts ERROR_DEFINITIONS. The `docs` URL on every API error points at /docs/errors/{code}/. */
export const ERROR_CODES = [
  { code: "not_found", status: 404, hint: "Check the id and organization scope.", more: "The id may be from another organization, may be mistyped (ids are prefixed: fm_, sb_, st_, ds_, rt_, dl_, prj_), or the resource may have been deleted. For a project slug, create it first or let the quickstart create it." },
  { code: "forbidden", status: 403, hint: "Use credentials with permission for this operation.", more: "API keys carry scopes: manage ⊇ read ⊇ submit. A read key cannot create or change resources. Mint a manage key for setup work." },
  { code: "unauthorized", status: 401, hint: "Provide a session cookie or an Authorization: Bearer pb_live_… key.", more: "Everything under /v1 requires authentication. The public submit endpoint POST /s/{formId} does not." },
  { code: "validation_failed", status: 422, hint: "Correct the fields described in details and retry.", more: "details.issues lists each offending path and message. The request shape is defined in /openapi.json." },
  { code: "mapping_incomplete", status: 422, hint: "Map every required stream field before attaching.", more: "A stream schema's required fields must each have a source (from, const, or default) in the form's mapping. details lists the missing fields. This is raised at attach time so delivery time holds no surprises." },
  { code: "schema_violation", status: 422, hint: "Publish a compatible schema or correct the submitted fields.", more: "In enforce and managed modes a submission that fails validation is stored with status quarantined and reason schema_violation; a drift event is raised. Nothing is dropped." },
  { code: "payload_too_large", status: 413, hint: "Reduce the payload size, field count, or nesting depth.", more: "The submit endpoint accepts bodies up to 256 KB. File uploads are not supported in this phase." },
  { code: "unsupported_media_type", status: 415, hint: "File uploads are not supported yet; send text fields only.", more: "multipart/form-data is accepted for text parts. A file part returns this error." },
  { code: "rate_limited", status: 429, hint: "Retry after the indicated delay.", more: "Per-form, per-IP limits are configured in settings.rate_limit. The overflowing submission is still stored with status quarantined and reason rate_limited; Retry-After is set." },
  { code: "origin_rejected", status: 403, hint: "Add the site origin to the Form allowed origins.", more: "settings.allowed_origins restricts which sites may post and doubles as the CORS allowlist. The submission is stored as quarantined with reason origin_rejected." },
  { code: "idempotency_conflict", status: 409, hint: "Reuse the key only for the identical operation.", more: "An Idempotency-Key was replayed with a different method, path or body. Use a fresh key for a different operation." },
  { code: "conflict", status: 409, hint: "The resource already exists, or is still referenced elsewhere.", more: "Creates are idempotent by slug when if_exists: \"return\" is passed. Deleting a destination that routes still reference returns this code." },
  { code: "plan_limit_reached", status: 402, hint: "Change plan limits or remove an unused resource.", more: "Forms and destinations are checked at creation. Submissions over the monthly limit are still stored and flagged; delivery pauses until the plan allows." },
  { code: "expressions_not_enabled", status: 422, hint: "Use from, const, or default until expressions ship.", more: "Mapping expr entries and route filter/transform are reserved for the expression phase (JSONata, ADR-005)." },
  { code: "internal_error", status: 500, hint: "Retry; contact support if this persists.", more: "The request id is in the response headers; include it when reporting." },
] as const
