/**
 * Mirrors the public codes in packages/core/src/errors.ts ERROR_DEFINITIONS, plus
 * codes specific to the email-code route handlers. Keep it in sync whenever a new
 * public PostbagError ships so its `docs` deep link never resolves to a 404.
 * The `docs` URL on every API error points at /docs/errors/{code}/.
 */
export const ERROR_CODES = [
  {
    code: "not_found",
    status: 404,
    hint: "Check the id and organization scope.",
    more: "The id may be from another organization, may be mistyped (ids are prefixed: fm_, sb_, st_, ds_, rt_, dl_, prj_), or the resource may have been deleted. For a project slug, create it first or let the quickstart create it.",
  },
  {
    code: "forbidden",
    status: 403,
    hint: "Use credentials with permission for this operation.",
    more: "API keys carry scopes: manage ⊇ read ⊇ submit. A read key cannot create or change resources. Mint a manage key for setup work.",
  },
  {
    code: "unauthorized",
    status: 401,
    hint: "Provide a session cookie or an Authorization: Bearer pb_live_… key.",
    more: "Everything under /v1 requires authentication. The public submit endpoint POST /s/{formId} does not.",
  },
  {
    code: "validation_failed",
    status: 422,
    hint: "Correct the fields described in details and retry.",
    more: "details.issues lists each offending path and message. The request shape is defined in /openapi.json.",
  },
  {
    code: "mapping_incomplete",
    status: 422,
    hint: "Map every required stream field before attaching.",
    more: "A stream schema's required fields must each have a source (from, const, or default) in the form's mapping. details lists the missing fields. This is raised at attach time so delivery time holds no surprises.",
  },
  {
    code: "stream_schema_missing",
    status: 422,
    hint: "Attach a form that has a published schema or at least one submission — Postbag derives the stream's first schema from it — or publish one with POST /v1/streams/{id}/schema.",
    more: "A Stream delivers one shared shape, so it needs a Schema before sources can be Mapped onto it. You rarely have to write one: attaching the first Form to a Schema-less Stream publishes version 1 copied from that Form's published Schema, its inferred draft, or the fields seen in its recent Submissions, with an identity Mapping. This error means neither was possible — the source was a selector, or the Form has no Schema and no Submissions yet. Send one test Submission, publish the Form's Schema, or publish the Stream Schema directly.",
  },
  {
    code: "schema_violation",
    status: 422,
    hint: "Publish a compatible schema or correct the submitted fields.",
    more: "In enforce and managed modes a submission that fails validation is stored with status quarantined and reason schema_violation; a drift event is raised. Nothing is dropped.",
  },
  {
    code: "payload_too_large",
    status: 413,
    hint: "Reduce the payload size, field count, or nesting depth.",
    more: "A normal text Submission accepts bodies up to 256 KiB; multipart bodies have a 16 MiB aggregate ceiling plus the organization's per-file and per-Submission limits. An anonymous sandbox is deliberately narrower: 16 KiB, four nesting levels, and no files.",
  },
  {
    code: "unsupported_media_type",
    status: 415,
    hint: "Send JSON, URL-encoded data, or multipart form data supported by this endpoint.",
    more: "Normal Forms accept multipart files when private storage is configured. Anonymous sandbox Forms deliberately accept text fields only.",
  },
  {
    code: "attachment_too_large",
    status: 413,
    hint: "Use a smaller file or increase the organization's attachment limit.",
    more: "The file exceeded attachment_max_bytes for the organization's current plan. GET /v1/me reports the exact limit.",
  },
  {
    code: "attachment_limit_reached",
    status: 413,
    hint: "Remove attachments or increase the organization's per-Submission limit.",
    more: "The multipart body contained more file parts than attachments_per_submission reported by GET /v1/me.",
  },
  {
    code: "attachment_storage_limit_reached",
    status: 402,
    hint: "Delete old Submissions with attachments, or upgrade the organization's plan.",
    more: "Accepting these bytes would exceed the organization's retained private-object capacity. No incomplete Submission receipt was created.",
  },
  {
    code: "attachment_storage_unavailable",
    status: 503,
    hint: "Configure an S3-compatible private bucket, then retry the Submission.",
    more: "Postbag could not durably store every attachment, so it did not claim to accept the Submission.",
  },
  {
    code: "rate_limited",
    status: 429,
    hint: "Retry after the indicated delay.",
    more: "For a normal tenant Form, per-IP limits come from settings.rate_limit and an overflow is stored as quarantined. Anonymous sandbox creation is different: admission is rejected before a Form or Submission exists when the edge or active-sandbox source allowance is exhausted.",
  },
  {
    code: "origin_rejected",
    status: 403,
    hint: "Add the site origin to the Form allowed origins.",
    more: "settings.allowed_origins restricts which sites may post and doubles as the CORS allowlist. The submission is stored as quarantined with reason origin_rejected.",
  },
  {
    code: "idempotency_conflict",
    status: 409,
    hint: "Reuse the key only for the identical operation.",
    more: "An Idempotency-Key was replayed with a different method, path or body. Use a fresh key for a different operation.",
  },
  {
    code: "anonymous_quickstart_disabled",
    status: 503,
    hint: "Use POST /v1/auth/request-code, then the authenticated POST /v1/quickstart path.",
    more: "This instance is not accepting new anonymous sandboxes. Existing sandboxes can still be claimed and retention cleanup still runs. Self-hosted operators enable creation with ANONYMOUS_QUICKSTART_ENABLED=true.",
  },
  {
    code: "sandbox_unauthorized",
    status: 401,
    hint: "Provide the sandbox token using the documented Sandbox authorization scheme.",
    more: "Read a sandbox with Authorization: Sandbox <token>. Claim it with authenticated organization access plus Postbag-Sandbox-Token. Never put the capability in a URL or use it as Bearer authentication.",
  },
  {
    code: "sandbox_expired",
    status: 410,
    hint: "Create a new sandbox. Anonymous Forms expire after 24 hours.",
    more: "Expiry is checked on every sandbox operation. An expired, unclaimed sandbox and its bounded test Submissions are removed by retention cleanup; the token cannot extend or revive it.",
  },
  {
    code: "sandbox_limit_reached",
    status: 409,
    hint: "Claim this Form or create a new sandbox. A sandbox accepts at most five Submissions.",
    more: "The sixth anonymous attempt is rejected before a Submission row is inserted. The five accepted tests remain durable and readable until claim or expiry.",
  },
  {
    code: "sandbox_claimed",
    status: 410,
    hint: "This sandbox token has been consumed. Use the claimed Form through the authenticated API.",
    more: "Claiming keeps the same Form id and submit URL but permanently consumes the sandbox capability. Read and manage the Form with the claimant organization's session or API key.",
  },
  {
    code: "sandbox_claim_email_mismatch",
    status: 403,
    hint: "Sign in with the verified email address bound when this sandbox was created.",
    more: "The optional claim_email is a deliberate ownership binding. Authenticate as that exact verified address, or let an incorrectly bound sandbox expire and create another; Postbag does not expose or rewrite the stored email hash.",
  },
  {
    code: "sandbox_capacity_reached",
    status: 503,
    hint: "Use the authenticated quickstart path or retry after other anonymous sandboxes expire.",
    more: "The instance-wide active-sandbox ceiling is full. No Form was created and the idempotency key can be retried with the identical body after capacity becomes available.",
  },
  {
    code: "conflict",
    status: 409,
    hint: "The resource already exists, or is still referenced elsewhere.",
    more: 'Creates are idempotent by slug when if_exists: "return" is passed. Deleting a destination that routes still reference returns this code.',
  },
  {
    code: "plan_limit_reached",
    status: 402,
    hint: "Change plan limits or remove an unused resource.",
    more: "Forms and destinations are checked at creation. Submissions over the monthly limit are still stored and flagged. Once the plan allows, a manager releases each held Submission to queue Delivery.",
  },
  {
    code: "billing_disabled",
    status: 501,
    hint: "Set the Polar billing environment variables, or use this instance as self-hosted.",
    more: "Hosted checkout and portal routes require a complete Polar server, token, webhook secret and product catalog configuration. The self-host plan does not require billing.",
  },
  {
    code: "billing_product_unavailable",
    status: 422,
    hint: "Choose a plan and billing interval configured by this Postbag instance.",
    more: "The requested paid plan or monthly/yearly interval has no corresponding product id configured on this instance. Read the available plan catalog and retry with a listed combination.",
  },
  {
    code: "grant_not_found",
    status: 404,
    hint: "Check the code and try again.",
    more: "No complimentary plan grant matches the supplied code. Codes are treated as secrets and this response does not reveal any similar or expired code.",
  },
  {
    code: "grant_expired",
    status: 410,
    hint: "Ask whoever sent the code for a new one.",
    more: "The complimentary plan grant passed its expiry time before redemption. Expired grants cannot be revived by retrying.",
  },
  {
    code: "grant_revoked",
    status: 410,
    hint: "This code was revoked and can no longer be redeemed.",
    more: "A platform administrator revoked this complimentary plan grant. Ask the issuer for a replacement if access is still intended.",
  },
  {
    code: "grant_exhausted",
    status: 410,
    hint: "This code has already been redeemed the maximum number of times.",
    more: "The grant reached its configured redemption ceiling. Retrying the same code cannot add another organization.",
  },
  {
    code: "plan_is_billing",
    status: 409,
    hint: "This organization already pays for its plan — cancel the subscription first if you want to redeem a code instead.",
    more: "A complimentary grant never silently replaces an active paid subscription. Cancel through the billing portal and wait for the organization to leave its paid plan before redeeming.",
  },
  {
    code: "plan_not_upgrade",
    status: 409,
    hint: "This code's plan is not higher than the organization's current plan.",
    more: "Redeeming a grant must improve the organization's effective plan. Keep the current plan or obtain a grant for a higher tier.",
  },
  {
    code: "plan_is_complimentary",
    status: 409,
    hint: "This organization has complimentary access; billing does not apply while it is active.",
    more: "Checkout is blocked while a complimentary plan grant controls the organization. An operator must remove or let that access expire before paid billing can begin.",
  },
  {
    code: "expressions_not_enabled",
    status: 422,
    hint: "Use from, const, or default until expressions ship.",
    more: "Mapping expr entries and route filter/transform are reserved for the expression phase (JSONata, ADR-005).",
  },
  {
    code: "invitation_expired",
    status: 410,
    hint: "Ask an owner or admin to invite you again.",
    more: "The invitation passed its expiry time before acceptance. A new invitation creates a new token and expiry.",
  },
  {
    code: "invitation_already_used",
    status: 409,
    hint: "This invitation was already accepted or revoked.",
    more: "Invitation tokens are single-use. Open the organization normally if you already joined, or ask an owner/admin for a new invitation if it was revoked.",
  },
  {
    code: "invitation_email_mismatch",
    status: 403,
    hint: "Sign out and sign in (or up) with the invited email address, then accept again.",
    more: "Invitations are bound to one normalized email address. Postbag will not add a differently authenticated user or reveal the expected address through this error.",
  },
  {
    code: "last_owner",
    status: 409,
    hint: "Promote another member to owner first, or transfer ownership before removing yourself.",
    more: "Every organization must retain at least one owner. Demotion, removal and leave operations all enforce this invariant.",
  },
  {
    code: "internal_error",
    status: 500,
    hint: "Retry; contact support if this persists.",
    more: "The request id is in the response headers; include it when reporting.",
  },
  {
    code: "invalid_code",
    status: 401,
    hint: "That code is wrong or has expired — request a new one.",
    more: "POST /v1/auth/verify-code allows 3 attempts per code, and codes expire after 10 minutes. Call POST /v1/auth/request-code again for a fresh one.",
  },
  {
    code: "email_send_failed",
    status: 502,
    hint: "The code email could not be sent; request a new code in a moment.",
    more: "POST /v1/auth/request-code tried to email the code and the mail provider call failed (after one retry). Usually transient. If it persists on a self-hosted instance, check RESEND_API_KEY and that MAIL_FROM uses a verified sending domain.",
  },
  {
    code: "email_not_configured",
    status: 501,
    hint: "Set RESEND_API_KEY and MAIL_FROM on the server, or create a key in the dashboard.",
    more: "POST /v1/auth/request-code needs outbound email configured on this instance (self-host parity: it is optional). Until then, sign in to the dashboard and create an API key from Settings.",
  },
] as const
