import { createDb } from "@postbag/db"
import { stringify } from "yaml"

import { createApp } from "../app.js"
import { buildAuth } from "../authSetup.js"
import { createDestinationRegistry } from "../destinations/registry.js"
import type { Env } from "../env.js"
import { createLogger } from "../logger.js"

export const OPENAPI_HEADER_COMMENT = "# Generated by pnpm openapi:export — do not edit by hand.\n"

// The generated document commits to the two hosted-product URLs regardless of which
// APP_URL the generating process happens to run with — see the comment in app.ts next to
// `servers: [{ url: env.APP_URL }]`. A self-hosted operator's own live /openapi.json still
// reports their own APP_URL; only this generated artifact is pinned to the hosted product.
const GENERATED_SERVERS = [{ url: "https://postbag.dev" }, { url: "https://api.postbag.dev" }]

/**
 * Builds the app against a stub, unreachable DATABASE_URL — postgres.js connects lazily,
 * so nothing here ever opens a connection — and fetches its own `/openapi.json`, exactly
 * like a real client would. Used by both `scripts/export-openapi.ts` and
 * `src/openapi.test.ts` so the two can never drift from each other.
 */
export async function generateOpenapiDocument(): Promise<Record<string, unknown>> {
  const env: Env = {
    DATABASE_URL: "postgres://stub:stub@127.0.0.1:1/stub",
    NODE_ENV: "production",
    PORT: 3000,
    APP_URL: "https://postbag.dev",
    BETTER_AUTH_SECRET: "export-openapi-stub-secret-not-used",
    POSTBAG_ROLE: "api",
    TZ: "UTC",
    MAIL_FROM: "Postbag <notify@postbag.dev>",
    MIGRATE_ON_BOOT: false,
    RLS_ENFORCED: false,
    LEGACY_HOSTS: [],
  }
  const logger = createLogger(env)
  const client = createDb(env.DATABASE_URL)
  const auth = buildAuth(client.db, env)
  const destinations = createDestinationRegistry(env)
  const app = createApp({ db: client.db, env, logger, auth, destinations })

  const response = await app.request("/openapi.json")
  if (!response.ok) {
    throw new Error(`Failed to generate the OpenAPI document: HTTP ${response.status.toString()}`)
  }
  const doc = (await response.json()) as Record<string, unknown>
  await client.close()
  return { ...doc, servers: GENERATED_SERVERS }
}

/** The exact contents `pnpm openapi:export` writes to `api/openapi.yaml`. */
export async function generateOpenapiYaml(): Promise<string> {
  const doc = await generateOpenapiDocument()
  return OPENAPI_HEADER_COMMENT + stringify(doc)
}
